### ISSUE TITLE
Chart line colours not stable when add/remove categories

### ISSUE THREAD

**Issue by AnnCorp** [ONSdigital/sdg-indicators#2007]
One that got raised in user testing as causing confusion  because of inconsistency in line colour when you add/remove categories through the filtering.  Example to reproduce : go to https://datasciencecampus.github.io/sdg-indicators/3-2-1/
From Geography, select, England, Wales, Northern Ireland and Scotland
From Sex, select Female
You look at the Scotland line which is purple and Wales which is light blue
Deselect Norther Ireland so just have GB countries not all four UK countries
Scotland  becomes mustard colour and Wales becomes purple .
This doesn't happen when turn lines on and off by clicking on the legend - until or if can't fix could promote using  the legends to toggle line charts.

**Comment by shaneporter** [comment]
I thought about this earlier today when I was testing the colours, and I concur that it's an issue.

The problem is that the different data series are determined by interactions with the checkboxes. There is no concept of additive selections - the selections are translated into an order, and adding new selections may mean that existing selections are reshuffled.

I know this isn't ideal, but estimating a fix for this isn't particularly easy.

**Comment by AnnCorp** [comment]
Needs exploring further - this would not be a quick fix. 
One for Savvas? Explore further in user testing?

**Comment by AnnCorp** [comment]
Closing on this repo as now have ticket within Open SDG, hopefully fix will release in v1.2:
https://github.com/open-sdg/open-sdg/issues/559
