### ISSUE TITLE
Disaggregation subsetting issues

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#2916]
The disaggregation layout for some of the indicators is incorrect. 

I think that the site generation uses [edges.py](https://github.com/open-sdg/sdg-build/blob/master/sdg/edges.py) via the open-sdg [build](https://github.com/open-sdg/sdg-build/blob/master/sdg/build.py) script to specify how the disaggregations are read ([path.py](https://github.com/open-sdg/sdg-build/blob/master/sdg/path.py) may also play a role).

Can we amend these to fix the disaggregation problems reported by the Data team (details TBC).

**Comment by Norric1Admin** [comment]
An example of the problem can be seen in indicators [5.2.1](https://onsdigital.github.io/sdg-indicators/5-2-1/), [5.2.2](https://onsdigital.github.io/sdg-indicators/5-2-2/) and [16.1.3](https://onsdigital.github.io/sdg-indicators/16-1-3/).

The Data team said that the disaggregations in 16.1.3 have become a subset underneath Sex, and in 5.2.1 the Ethnic group category is listed as a sub category of Abuse category which is pretty questionable!

**Comment by Norric1Admin** [comment]
@dougmet Are you available this Wednesday (20 Feb) to discuss this with Data?

**Comment by dougmet** [comment]
(writeup of call. Many thank @mikebolton10 )

Let’s consider a simplified view of https://onsdigital.github.io/sdg-indicators/5-2-2/

The edge detection finds the following (not all listed)
```
Sex -> Region
Sex -> Age
Sex -> Ethinicity
Sex -> … everything *except* the Abuse Perpetrator/Category/Sub-Category
Abuse perpetrator -> Abuse sub-category
Abuse category -> Abuse sub-category
Ethnicity -> Ethnic group
```

This translates to a tree (not all shown):

```
        Sex                Abuse Perp    Abuse Cat
   --------------------...     |_____________|
   |     |       |                    |
Region  Age  Ethnicity           Abuse Sub-Cat 
                 |          
            Ethnic Group
```

So the issues we have are:
1.	Most of the data is only reported disaggregated by Sex, but it’s not a parent in the true sense of the word.
2.	We have deeper nesting than the site is designed for.  E.g. Sex -> Ethnicity -> Ethnic Group.
3.	Multiple Parents. This is not a tree (it’s a DAG). We don’t really want the Perp-> Sub-Cat relationship.

### 1. Missing Aggregations

This is a reasonably common issue when we don’t have access to the underlying data. Also, there’s a sense for the goal-5 data that everything really is split by Sex. So it’s possible some restructuring could make the Sex column more of a “Units” style column that sits above everything. Otherwise we need to make a requirement that somehow tells the NRP that it’s not a real parent.

### 2. Deep Nesting

I think the site should support deeper nesting. Ticket raised open-sdg/open-sdg#86 on open-sdg to allow deeper nesting. It will start looking silly after 3 but that’s your responsibility.

### 3. Multiple Parents

This doesn’t feel right. It’s related to 1 in that maybe we can manually override the edge. Another option would be to automatically trim multiple-parents. We could make a rule by which the primary parent is chosen (so for example in this dataset you’d choose the parent closest to it in the columns). It’s a bit similar to how we trim grandparent edges. This sort of thing would need heavily documenting.

## Conclusion

We’re a long way towards refining these problems into technical requirements so that we can fix them. Let’s do a couple more rounds on issues 1, and 3, to agree how it should work.

**Comment by AnnCorp** [comment]
Discussed at catchup with Doug and SDG platform team.
(1) and (3) need more input from SDG  data team re what would want these scenarios/indicators to look like.
(2) Ticket opened on open/adg but likely will leave for development by Brock/Savvas - use any remaining time from Doug to refine specification.

**Comment by AnnCorp** [comment]
Clsoign as covered by a ticket in Open SDG - see https://github.com/open-sdg/open-sdg/issues/390
