### ISSUE TITLE
Move test server to ONSDigital infrastructure (Savvas)

### ISSUE THREAD

**Issue by AnnCorp** [ONSdigital/sdg-indicators#2917]
Currently test site uses Mango infrastructure - need to move this to ONS kit.
@dougmet to add more details to the ticket please ahead of discussing with Savvas.

**Comment by dougmet** [comment]
Current test server is a pretty small VM in GCP. It's a g1-small (1 vCPU, 1.7 GB memory) and this has been more than adequate for our purposes.

It's running apache (although it would run just fine with nginx) and a non-admin user has an ssh deployment key that is stored encrypted in the Travis repo. This is used to push builds back to the server in the right location.

To completely match it you would need:

1. Setup Apache/Nginx
2. Create a user `travis` and link their `www` folder to the `www` folder in apache.
3. Distribute keys to Travis and the Server.

That's it. I'm thinking of adding a cleanup script to remove builds of more than 4 weeks old or something. Otherwise it's a simple web server where we can push the sites.

Also considering adding an .htaccess password to make it a little more private. Had considered IP ranges but as people were working from quite a few locations this seemed a little restrictive for something that is not sensitive.

**Comment by Norric1Admin** [comment]
Relevant to https://github.com/ONSdigital/sdg-indicators/issues/2920

**Comment by AnnCorp** [comment]
@SavvasStephanides actioned this in 2019.
