### ISSUE TITLE
Accessibility audit (Savvas)

### ISSUE THREAD

**Issue by AnnCorp** [ONSdigital/sdg-indicators#2961]
Formal comprehensive testing by [Digital Accessibility Centre](http://digitalaccessibilitycentre.org/)  provisionally scheduled to start 1 April.
Need initial accessibility audit ahead of this to identify (and then fix) any key issues before DAC testing.
@ian-kent will provide details of the software to be used for this.

**Comment by AnnCorp** [comment]
Hi @ian-kent @SavvasStephanides if the testing starts on 1 April, we need all changes to go through on our site by cop Thurs 28 April, ahead of briefing meeting with DAC on Fri 29th.
Do we have confirmation yet of which software should use please? Thanks!

**Comment by SavvasStephanides** [comment]
@ian-kent @AnnCorp any news on how to approach this? I'm sure there is software that we can use to utilise to test for accessibility. If you have something in mind please share. 

In the meantime I've found this link with some interesting things to consider: https://www.guru99.com/accessibility-testing.html

**Comment by AnnCorp** [comment]
@SavvasStephanides I previously mentioned Wave to Ian (think that's the one Benjy Stanton mentioned to my team previously) and its also listed as one of the options for automated testing in the GDS service standard. https://www.gov.uk/service-manual/helping-people-to-use-your-service/testing-for-accessibility. Probably worth starting off with the GDS stuff as that's ultimately what we'll be assessed against.

**Comment by SavvasStephanides** [comment]
There don't seem to be any significant violations of accessibility. Seems you have all made a brilliant job at taking accessibility into account:

![](https://i.imgur.com/5xlqDHg.png)

Only something about redundant links on 3 separate occassions:

![](https://i.imgur.com/6pPlW3l.png)

**Comment by SavvasStephanides** [comment]
I've run an accessibility check based on [18F accessibility guide](https://accessibility.18f.gov/) and Tenior.io. Here are my observations:

# Tenior.io Results

## Invalid hypertext reference

There are several instances where links like these appear: `<a href="javascript:void(0)">`. These links result in functionalities that are unclear for users of (for example) screen readers. An example is the search link at the top which opens the search bar.

# 18F guide

## Keyboard access

The SDG site does a pretty good job at keyboard navigation. No significant issues here.

A very small thing I noticed is that once a user presses the `spacebar` to tick a checkbox, it goes back to the top of the form. I'm not sure if this is intentional.

## Images

Good and clear descriptions of all images with `alt` tags.

## Colour and contrast

Some contrast "violations" present in the site. A few examples are from the colours in the goals "squares" in juxtaposition with the text in front.

For example, Goal 7:

<img width="723" alt="Screen Shot 2019-03-15 at 15 11 57" src="https://user-images.githubusercontent.com/478770/54441487-cb86ee80-4734-11e9-9ca5-e5835cc1ccd4.png">

Or goal 9:

<img width="725" alt="Screen Shot 2019-03-15 at 15 17 32" src="https://user-images.githubusercontent.com/478770/54441883-831c0080-4735-11e9-82a1-3670020cbdfd.png">

I do understand these colours have been chosen by UN, but I think we can try and improve as much as we can for things we have control over (eg. The top bars at the page of each goal)

## Forms

For the disaggregation fields, each checkbox is part of  its label, 

```html
<label>Check <input type="checkbox"></label>
```

...instead of the more common usage of having a `<label for="the-checkbox">Check</label>` followed by the `<input id="the-checkbox type="checkbox">`. I'm not sure if this would cause problems for certain users but it is worth checking.

## Flashing

No problems with flashing text/images

## Page titles

18F suggests we include the site name at the page title:

> The title should describe the web site as well as the specific page being displayed by the site.

Currently we only show the page title.

## Headings

Good use of headings although I'm a bit concerned with the size inconsistency of `<h1>` and `<h2>` tags which can confuse screen reader users:

![image](https://user-images.githubusercontent.com/478770/54444218-2e2eb900-473a-11e9-92ea-f7b67f6a017b.png)

## Links and repetitive content

A small concern with the "search" link on the home page which may confuse some users which in the words of the guide:

> Often, screen reader users won't read through an entire page to find what they are looking for. They simply move from link to link.

They might get confused when they hear "or search" without context.

Great use of the keyboard otherwise, especially with a "skip to main content" link.

**Comment by AnnCorp** [comment]
Closing as various accessibility checks now built in using pa11y plus further DAC testing schedled for August.
