### ISSUE TITLE
Test Open SDG Quick Start guide (Savvas)

### ISSUE THREAD

**Issue by AnnCorp** [ONSdigital/sdg-indicators#2962]
Test the documentation in [Open SDG Quick Start](https://open-sdg.readthedocs.io/en/latest/) guide
Assess if any gaps in the documentation or anything not clear.
To note: @Norric1Admin had done a more detailed step-by-step version in UK site wiki aimed more at first-time users and those with technical skills but not necessarily developers https://github.com/ONSdigital/sdg-indicators/wiki/Clone-your-own%3A-step-by-step-instructions-%28Windows%29. 
Ultimate aim should probably be or one set of guidance - need to consider if can achieve this and how, without losing the detail required by some users.

**Comment by SavvasStephanides** [comment]
Did my first attempt at following the Quick Started guide and got stuck at the part where I'm supposed to add my private key to CircleCI ("Add projects to CircleCI.com" section, step 7). I keep getting the error below:

![CircleCI error](https://i.imgur.com/AmIA2no.png) 

I'll try and fix the error and make a note of my findings.

**Comment by Norric1Admin** [comment]
Thanks @SavvasStephanides - this could be a shortfall in the guidance, or a symptom of using a Mac. Guidance is based around Circle (rather than Travis) CI so this may also be a blocker for us. Interested to see if there's a way around this.

**Comment by SavvasStephanides** [comment]
> Thanks @SavvasStephanides - this could be a shortfall in the guidance, or a symptom of using a Mac. 

That's an interesting point. It'd be interesting to see if it works on Windows. My assumption would be that attempting this on Linux/Ubuntu would have a similar behaviour due to its Unix core.

> Guidance is based around Circle (rather than Travis) CI so this may also be a blocker for us. Interested to see if there's a way around this.

I'm giving the Travis guide a go and see if it works. I'll keep you posted.

**Comment by SavvasStephanides** [comment]
Update on the Travis guide. This guide is relatively straight forward although my deployment fails at the end. Not sure if it's my fault or is it something missing from the guide. Here's my Travis log:

<img width="539" alt="screen shot 2019-03-07 at 12 33 18" src="https://user-images.githubusercontent.com/478770/53957120-7401d680-40d5-11e9-8418-02acf9ff041d.png">

**Comment by Norric1Admin** [comment]
Thanks Savvas, I'll have a look at this and get back to you.

**Comment by dougmet** [comment]
`iv undefined` looks like the secret environment variable that is used to decrypt the keys. So maybe something didn't go well with that. If this deployment is the `deploy_testing` one then this won't work because you won't have the right keys to access the server.

deployment has become quite involved on the latest versions. We need to look at simplifying it. We can look at this together on Monday.

(hi and welcome btw!)

**Comment by Norric1Admin** [comment]
Savvas, did you add the keys to your machine using ssh-agent?

**Comment by Norric1Admin** [comment]
Also, open Travis and view the Settings of both repos - the 'encrypted_key/iv' variables should match your public keys. Do both repos also have a TARGET_REPO variable? Finally, view your deploy key in GitHub and see whether it has been activated yet (it turns green).

**Comment by SavvasStephanides** [comment]
Hi @dougmet. Thanks for your reply. It seems like something to do with decrypting the data in Travis. I've double checked that I used the correct identifier code. I'm not sure what `deploy_testing` is.

@Norric1Admin I've generated my keys using the `ssh-keygen` method.

**Comment by SavvasStephanides** [comment]
@Norric1Admin. My replies below:

> Also, open Travis and view the Settings of both repos - the 'encrypted_key/iv' variables should match your public keys. 

I'm not sure how to check this. The values are hidden in Travis

> Do both repos also have a `TARGET_REPO` variable?

Yes they do. Although it's not clear what the value of the `TARGET_REPO` should be. Is it `git@github.com:SavvasStephanides/sdg-indicators.git`, `SavvasStephanides/sdg-indicators.git`, `SavvasStephanides/sdg-indicators` or something else (since the guide says "the URL")? I've tried all three above without much luck.

> Finally, view your deploy key in GitHub and see whether it has been activated yet (it turns green).

Yes the deploy keys have been turned green for both `sdg-data` and `sdg-indicators`

**Comment by Norric1Admin** [comment]
@SavvasStephanides 

> I'm not sure how to check this. The values are hidden in Travis.
The values in 'encrypted_**********_iv/key' should match those you pasted into scripts/deploy.

> It's not clear what the value of the TARGET_REPO should be.
TARGET_REPO should be the 'sustainable-development...' (production/live) repo in SSH format.  I'm not sure which URL you are pointing to, but for the [UK](https://github.com/sustainabledevelopment-uk/sustainabledevelopment-uk.github.io) it is `git@github.com:sustainabledevelopment-uk/sustainabledevelopment-uk.github.io.git`).

> Yes the deploy keys have been turned green for both sdg-data and sdg-indicators
Great :+1: This is a good sign as we probably don't have to use the [ssh-agent](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) step. Try committing your changes to the master branch for both repos once you've updated TARGET_REPO.

**Comment by SavvasStephanides** [comment]
> The values in 'encrypted_**********_iv/key' should match those you pasted into scripts/deploy.

🙌Bingo! The values are different in Travis and my scripts. Not sure how it ended up this way. It has been automatically added by Travis and I didn't bother to check it. 🙄

**Comment by dougmet** [comment]
It's hard work. I wish you could just paste in private keys through the web browser.

**Comment by SavvasStephanides** [comment]
On second check, `sdg-data` actually has the correct values. `sdg-indicators` doesn't. 🤔

**Comment by SavvasStephanides** [comment]
Bad news. Still getting the same error with the correct encrypted key values 🙁

**Comment by dougmet** [comment]
Regarding circle ci keys. Might be worth asking @brockfanning because he was going to update the docs at some point so that the `ssh-keygen` command was different (something involving pam).

**Comment by brockfanning** [comment]
@SavvasStephanides @dougmet Hey all, yes at one point I got the impression that the ssh-keygen command needed to be different. So I made [this commit](https://github.com/open-sdg/open-sdg/commit/3cff89ff4c9c1dfb312bb92ddcf35ab6028d7873#diff-216a3091bfd741f853e81440b2a67030). But then that one gave me problems, so I reverted it.

I think it does unfortunately depend on the OS you're using. So we might need to put in special instructions depending on OS. Savvas maybe try generating the keys using `ssh-keygen -m pem -t rsa -b 4096 -C "my-email-address@example.com"` and see if that is any better for CircleCI?

**Comment by SavvasStephanides** [comment]
Thank you for your response @brockfanning. I'll give the Quick Start guide another go with your `ssh-keygen` suggestion and get back to you 👍

**Comment by Norric1Admin** [comment]
@SavvasStephanides I think the problem is that your encrypted key values in the [master branch](https://github.com/SavvasStephanides/sdg-indicators/blob/master/scripts/deploy/deploy.sh) have not been replaced yet. I recommend pushing 'develop' to 'master' to resolve the issue.

Also, what is the URL for your production site?

**Comment by SavvasStephanides** [comment]
### Quick Start (CircleCI) Guide progress

@brockfanning's `ssh-keygen` update helped me get unstuck from that private key I was getting so thanks to all for your valuable help.

I've managed to get to the end of the guide but my CircleCI builds fail each repository for different reasons:

#### site-starter

```
#!/bin/bash -eo pipefail
bash scripts/deploy/circleci/deploy_staging.sh
sed: can't read /home/circleci/.ssh/config: No such file or directory
Cloning into 'out'...
ssh: Could not resolve hostname gh-staging: Name or service not known

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
scripts/deploy/circleci/deploy_staging.sh: line 25: cd: out: No such file or directory
error: pathspec 'gh-pages' did not match any file(s) known to git.
Switched to a new branch 'gh-pages'
cp: cannot create directory 'out/.': No such file or directory
cp: cannot stat '.circleci/.': No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Exited with code 128
```

#### data-starter

````
#!/bin/bash -eo pipefail
bash scripts/deploy/circleci/deploy_staging.sh
sed: can't read /home/circleci/.ssh/config: No such file or directory
Cloning into 'out'...
ssh: Could not resolve hostname gh-staging: Name or service not known

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
scripts/deploy/circleci/deploy_staging.sh: line 25: cd: out: No such file or directory
error: pathspec 'gh-pages' did not match any file(s) known to git.
Switched to a new branch 'gh-pages'
cp: cannot create directory ‘out/.’: No such file or directory
cp: cannot stat ‘.circleci/.’: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Exited with code 128
````

Here are my [site-starter](https://github.com/SavvasStephanides/open-sdg-site-starter) and [data-starter](https://github.com/SavvasStephanides/open-sdg-data-starter) forks if that helps.

Thanks again for your help.

**Comment by SavvasStephanides** [comment]
> Also, what is the URL for your production site?

@Norric1Admin if you mean from the Travis guide (sorry this thread became a bit convoluted switching between guides) then my production site is https://sustainabledevelopment-cy.github.io/

**Comment by brockfanning** [comment]
@SavvasStephanides Cool, let's try and get the data repository working first. In the Quick Start under "Add projects to CircleCI.com", can you confirm step 6? The string "gh-staging" needs to be exact, because it corresponds to [this line](https://github.com/SavvasStephanides/open-sdg-data-starter/blob/develop/scripts/deploy/circleci/deploy_staging.sh#L22) in the deploy script.

If you're sure that was done correctly, I would also double-check that this [fingerprint](https://github.com/SavvasStephanides/open-sdg-data-starter/blob/develop/.circleci/config.yml#L62) is correct.

**Comment by SavvasStephanides** [comment]
So this is slightly confusing: I've just visited CircleCI and the `data` build seems to have succeeded (it was showing as failed before). Maybe it took a bit to update on CircleCI after I changed `_config.yml`.

![image](https://user-images.githubusercontent.com/478770/54025274-f354e000-4191-11e9-8592-7c59701148c6.png)

However https://savvasstephanides.github.io/open-sdg-data-starter/ still shows as 404 and the `site` build still fails.

Thanks.

**Comment by brockfanning** [comment]
Ah, you're right, your data repo is all set. See some output [here](https://savvasstephanides.github.io/open-sdg-data-starter/meta/all.json).

So on to the site repo: Can you confirm that [this fingerprint](https://github.com/SavvasStephanides/open-sdg-site-starter/blob/develop/.circleci/config.yml#L75) is correct? My suspicion is that "P" shouldn't be there.

**Comment by SavvasStephanides** [comment]
🚀SUCCESS!! 🚀

Yes you are correct the fingerprint had an extra P in there, no idea how it got there. Thanks so much for your help @brockfanning!

**Comment by SavvasStephanides** [comment]
After a week of trying and trying again and with lots of help from @dougmet I have _finally_ managed to get Travis CI up and running. https://sustainabledevelopment-cyprus.github.io/

The country choice may or may not be coincidental. 🙄

**Comment by AnnCorp** [comment]
Just had a thought, is the Cyprus test version hidden from Google search - if not, may be worth bunging something on it to show test site, not the real thing. Just incase...

**Comment by SavvasStephanides** [comment]
I don't think so. It's just been deployed and I don't think it's been linked from anywhere else in order for Google to see it and crawl it.

**Comment by SavvasStephanides** [comment]
Hi @Norric1Admin. Glad to finally get it working. Here's from what I remember:

### Specific errors

#### Bundle Gem version error

That was one of the first errors I faced on Travis was that the `bundle` version was wrong. I think it's expecting version 2.0 while it was something else. This can be either configured in `Gemfile.lock` or just delete `Gemfile.lock` altogether.

#### Deployment error `iv undefined`

This was a problem I faced when deploying both `sdg-data` and `sdg-indicators`. This usually happens when there are already environment variables defined in the Travis instance of the repository (for example when the build failed first time and you're fixing an error). Doug's advice, which worked, was to delete any previous environment variables (encrypted key and iv) before re-committing.

#### File `scripts/deploy/deploy_key_test` is missing error

I was also advised to delete [these lines](https://github.com/SavvasStephanides/sdg-indicators/commit/7bef3ef4b2fb8b929421060c740b8e8e982305be) from `.travis.yml`because it was looking for a (test) file that doesn't exist.

_There might be more but they slip my mind right now_

### General comments

Overall the guide has been rather confusing to follow probably because of the numerous changes to both the document and the code over time. I understand it is difficult to keep the two consistent. I can work on improving the guide or work together to make it easier to follow. Also one of the reasons why I suggest [automating](https://github.com/ONSdigital/sdg-indicators/issues/2984) as much as we can.

I hope this has been constructive.

**Comment by Norric1Admin** [comment]
Thanks @SavvasStephanides this was very informative. A few questions:
- Is deleting Gemfile.lock safe? If so, happy for this to be added to guidance as a troubleshooting step. We delete index.lock in order to backup the repos, but am not certain if Gemfile.lock has a function. If you're uncertain, best to recommend configuring the file instead.
- I also encountered `iv undefined` when I was writing the guidance, so perhaps it's a common error. If there isn't already, it's definitely worth having a section on this.
- Re the change to the Travis file, can you open a pull request on this and get @dougmet's thoughts? Seems like a good solution to have this applied to all Travis files, but I'm unsure what these lines do.
- Glad to accept changes to the guidance to make it more accessible, but please investigate [automation](https://github.com/ONSdigital/sdg-indicators/issues/2984) first to avoid reworking. Keen to see  how this progresses.

**Comment by Norric1Admin** [comment]
P.S. The Ubuntu installation is required for Windows machines in order to encrypt `keys.tar` - one of the more convoluted steps of the guidance. If there is a way to encrypt the keys without Ubuntu (perhaps using  some sort of automation) then this would save users a lot of headache.

**Comment by dougmet** [comment]
It's anything unixy (~ anything but Windows). So Ubuntu, all Linux distros, Mac OS. We *could* look at moving the whole project to circle, where we think key management is easier.

It's funny because no one (except Travis) needs the private keys. You feel like you could run the whole thing from Travis, or an external app, if they had that feature. Then you just download the public keys and put them in the right place. We should keep thinking about how to smooth this over.

**Comment by dougmet** [comment]
> I was also advised to delete these lines from .travis.yml because it was looking for a (test) file that doesn't exist.

You can't remove this from the UK site. This deploys branches to the testing server.

**Comment by brockfanning** [comment]
A note about Travis - there is also [this approach](https://docs.travis-ci.com/user/deployment/pages/) using only a personal Github API token. **But this has some downsides** - I don't remember the specifics but I believe (from a while back when I last tried it) it's not totally secure, in that project collaborators could somehow get the API token. See the "NOTE" [here](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials). It's also probably not great to have the deployment depend on a single user's API token.

So, not the most helpful comment I guess :) - just adding for reference.

**Comment by SavvasStephanides** [comment]
Hi @Norric1Admin, please see my comments below:

> Is deleting Gemfile.lock safe? If so, happy for this to be added to guidance as a troubleshooting step. We delete index.lock in order to backup the repos, but am not certain if Gemfile.lock has a function. If you're uncertain, best to recommend configuring the file instead.

From my experience it hasn't caused any significant problems but it has solved the problem of `bundle` version incompatibility.

> I also encountered iv undefined when I was writing the guidance, so perhaps it's a common error. If there isn't already, it's definitely worth having a section on this.

I agree. It seems to be quite a common issue (I've had it way too many times). It seems to be just a matter of disagreement of deploy keys between Github and Travis when some keys are already present before deployment (like when deployment fails and you try again). Might be worth deleting the deploy keys from Travis before deploying.

> Re the change to the Travis file, can you open a pull request on this and get @dougmet's thoughts? Seems like a good solution to have this applied to all Travis files, but I'm unsure what these lines do.

@dougmet what do you think? Worth making a pull request for [this](https://github.com/SavvasStephanides/sdg-indicators/commit/7bef3ef4b2fb8b929421060c740b8e8e982305be)?

> Glad to accept changes to the guidance to make it more accessible, but please investigate automation first to avoid reworking. Keen to see how this progresses.

This is one of the reasons I advocate for a better architecture solution. I'll see what I can  do automation-wise.

**Comment by Norric1Admin** [comment]
> @dougmet what do you think? Worth making a pull request for this?
Doug has advised not to do this.

> This is one of the reasons I advocate for a better architecture solution. I'll see what I can do automation-wise.
Thanks. Best to hold fire on updating the guidance for now until we have discussed the potential for Circle CI adoption next Friday (29th). Please wait until then before doing too much on automation.

**Comment by dougmet** [comment]
I'm a little lost as to which changes to the travis file we're discussing. There was talk of moving the `keys.enc` to the root location so that we don't need to handle decrypting them ourselves. I think this is a good shout and should save a lot of headaches copying environment variables between scripts. I'll work up a PR for it.

**Comment by dougmet** [comment]
I've had a play in the `travis-does-keys` branch. I have a concern with putting the decryption in the travis file because it does it before you build the site and if you're not careful you can publish the keys.

One thing to make it a little less painful is to put the decryption in a `decrypt_keys.sh` so there's only one place you need to edit the variable names. I'm looking into how to make travis encrypt-file use a simpler variable name too, then you wouldn't need to update any scripts at all.

**Comment by AnnCorp** [comment]
Closing - testing was undertaken and most recent guide has been tested by James.
