### ISSUE TITLE
Remove files that cause platform to break when upgrading to Open SDG 1.0

### ISSUE THREAD

**Issue by SavvasStephanides** [ONSdigital/sdg-indicators#3389]
There are some files that override the Open SDG files. These files break the platform when upgrading to Open SDG 1.0. Deleting them fixes the problems. These are the files:

*  https://github.com/ONSdigital/sdg-indicators/blob/develop/_includes/assets/js/plugins/jquery.sdgMap.js

* https://github.com/ONSdigital/sdg-indicators/blob/develop/_includes/assets/js/plugins/leaflet.yearSlider.js

* https://github.com/ONSdigital/sdg-indicators/blob/develop/_includes/assets/js/indicatorView.js

Are these files needed or can they be deleted?

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides just looked at this - I overwrote this file because our data downloads weren't working properly on the version of Open SDG we were pointing at.

The Download Chart CSV button is supposed to download whatever data has been selected on the chart, but it was only downloading headline data, no matter what data had been selected.

That file can be deleted when we upgrade to v1

**Comment by LucyGwilliamAdmin** [comment]
As for the other two overwrites, it looks like there's been quite a lot of changes to these files since we have started overwriting them. 

I think it might be worth taking a look at what the differences are if we stop overwriting them e.g. what functionality changes, are the maps still acting as we want them too.

**Comment by SavvasStephanides** [comment]
Thanks @LucyGwilliamAdmin 

You're right. The maps (and year slider) do seem to break when the files are removed.

![image](https://user-images.githubusercontent.com/478770/77168362-9a5f9d80-6aaf-11ea-8a41-101decff2b86.png)

It's going to take quite a bit of work to match the changes with 1.0 changes if we want the maps to work.

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin @SavvasStephanides is there anything to be added to this please - all resolved with successful move to v1.0.0?

**Comment by SavvasStephanides** [comment]
Yes we can close this.
