### ISSUE TITLE
Cookie consent form

### ISSUE THREAD

**Issue by brockfanning** [ONSdigital/sdg-indicators#3523]
Opening this to continue UK-specific discussion from https://github.com/open-sdg/open-sdg/issues/1231

I'll put up a PR shortly, but still have a few questions for @phillipgardiner:

Regarding Hotjar:

1. I don't believe Hotjar is implemented on the site at this time, right? Would you like me to add it to the site as part of this ticket?
2. Either way, will it eventually be on production-only, staging-only, or both?

Regarding the confirmation box that appears after a user has saved their settings on the cookie settings form: 

1. It includes a link to "Go back to the page you were looking at" - but my understanding is that this form is on its own dedicated page, which I've assumed would be the current [cookies page](https://sdgdata.gov.uk/cookies/). I suspect my understanding is wrong so just wanted clarification there. What would be an example of the series of steps where a user would use the "Go back to the page you were looking at" link?
2. In the mockup the confirmation box appears at the top of the page, but the "Save changes" button is far down the page, which means that users wouldn't see the confirmation unless they scroll back up. Any ideas on how to deal with that?
3. Is this confirmation box taken from any GDS component that I could use?

**Comment by phillipgardiner** [comment]
@brockfanning morning. Good questions, i'll try my best to answer below. 

1. _I don't believe Hotjar is implemented on the site at this time, right? Would you like me to add it to the site as part of this ticket?_
No I don't believe it is yet. We have a ticket in the UK trello board assigned to Lucy but its not done yet due to being blocked? - is this correct @LucyGwilliamAdmin. I'm sure Lucy wont mind you adding it on her behalf. if this helps: https://help.hotjar.com/hc/en-us/articles/115009336727-How-to-Install-your-Hotjar-Tracking-Code and here is the code you will need..
[Hotjar_installation_code.docx](https://github.com/ONSdigital/sdg-indicators/files/6685359/Hotjar_installation_code.docx)

2. _Either way, will it eventually be on production-only, staging-only, or both?_
Good question, from my perspective we will only really be capturing the user data on the live SDG website. However it may be worth replicating it across the other sites in order to support any testing (both UX and functional testing we may do). Just so we know all code / experience is exactly the same across all sites. Again @LucyGwilliamAdmin do you have a view on this?

In regards to the confirmation box:

1 _It includes a link to "Go back to the page you were looking at" - but my understanding is that this form is on its own dedicated page, which I've assumed would be the current cookies page. I suspect my understanding is wrong so just wanted clarification there. What would be an example of the series of steps where a user would use the "Go back to the page you were looking at" link?_

Sorry not sure I entirely understand the question. The confirmation message would appear at the top of the cookies page. An example of the steps may be: Pop up banner appears > Clicks 'view cookies' link > View cookie page and make selections > Selects 'save cookie settings button > Confirmation message appears on cookies page > Selects to go back to previous page > Taken back to whatever page they were on when the cookie banner appeared.

Alternatively they could be on any page on the site > Clicks 'Cookies' in page footer > View cookie page and make selections > Selects 'save cookie settings button > Confirmation message appears on cookie page > Selects to go back to previous page > Taken back to whatever page they were viewing before they clicked on the cookie link in the footer.

2. _In the mockup the confirmation box appears at the top of the page, but the "Save changes" button is far down the page, which means that users wouldn't see the confirmation unless they scroll back up. Any ideas on how to deal with that?_

The expectation is that on clicking the buttons you are taken back to the top of the page (a bit like a back to top link). You can see an example here: [(https://www.gov.uk/help/cookies)]

3. _Is this confirmation box taken from any GDS component that I could use_

Sure: https://design-system.service.gov.uk/components/notification-banner/. There is also a specific example about 2/3rds of thew way down this page: https://design-system.service.gov.uk/patterns/cookies-page/

As a final note just to let you know, I was working on adding lots of supporting notes etc to the mock ups I have produced including links etc to the relevant components. Hopefully this will help a bit - i just have not finished it yet :)

**Comment by phillipgardiner** [comment]
@brockfanning Attaching the latest versions of the Cookie_Journey and Cookie_Page documents, following the decision to include 'contrast' cookie as an essential. Any questions please feel free to reach out :)

[Cookie_Journey_v3.pdf](https://github.com/ONSdigital/sdg-indicators/files/6694781/Cookie_Journey_v3.pdf)
[Cookies_Page_v3.pdf](https://github.com/ONSdigital/sdg-indicators/files/6694783/Cookies_Page_v3.pdf)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning re. Hotjar being added - If you could add Hotjar as part of this ticket, that would be great please.

If it's on both staging and prod, does it need two different setups?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think that's up to you, but we can start with a single setup for both. Can you point me to the code changes needed to add it?

**Comment by phillipgardiner** [comment]
@brockfanning https://github.com/ONSdigital/sdg-indicators/issues/3523#issuecomment-864873556

**Comment by phillipgardiner** [comment]
> @LucyGwilliamAdmin I think that's up to you, but we can start with a single setup for both. Can you point me to the code changes needed to add it

@brockfanning @LucyGwilliamAdmin I think you can do it with a single setup https://help.hotjar.com/hc/en-us/articles/115011773408-How-to-Track-Multiple-Subdomains. However, as were are using the free version we have limits like only working for 2000 pageviews per day. We get close to this on the live site only, so perhaps we will need to keep it off other set ups for now. Happy to discuss on slack or something as I don't understand the impact of having it across setups v not.

**Comment by brockfanning** [comment]
A new PR is up which includes Hotjar and the latest mockups, I think: https://github.com/ONSdigital/sdg-indicators/pull/3532

**Comment by LucyGwilliamAdmin** [comment]
Closing this as implemented a while back
