### ISSUE TITLE
Update cookies page

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [ONSdigital/sdg-indicators#3612]
Updates required below

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning. Have mocked up the required changes to the cookies page in order to take into account the need for a legend etc. This has meant a number of small changes to that section. These are documented on the attached file: .
[Cookies_Page_Update.pdf](https://github.com/ONSdigital/sdg-indicators/files/9040810/Cookies_Page_Update.pdf)

**Comment by LucyGwilliamAdmin** [comment]
Additionally we need to add legend to radio button fieldset
